#!/usr/bin/env ruby
require 'pathname'
require 'tempfile'

def open_browser(path)
  case RUBY_PLATFORM
  when /darwin/
    system 'open', path
  when /mswin(?!ce)|mingw|cygwin|bccwin/
    system 'start', path
  else
    system 'firefox', path
  end
end

t = Tempfile.new('few')
File.open(t.path, 'w') {|io|
  a =
    if true
      ARGF.read
    else
      # debug is love!!!
      File.read('README.md')
    end
  a = a.gsub(/\r?\n/, "<br/>\n")
  a = a.gsub(/^\s+/) {|m| '<font color=white>' + '_'*m.size + '</font>' }
  io.puts a
}
t.close
File.rename(t.path, html = t.path + '.html')
open_browser(html)
